[project]
name = "qx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-ai>=0.2.3",
    "python-dotenv>=1.1.0",
    "prompt-toolkit>=3.0.0", # Added prompt-toolkit
]

[tool.setuptools]
script-files = ["bin/qx"]