[project]
name = "qx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-ai>=0.2.4",
    "python-dotenv>=1.1.0",
    "prompt-toolkit>=3.0.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
qx = "qx.main:main"  # Corrected: points to 'qx.main'

# Add this section to tell setuptools to look for packages in the 'src' directory.
# It will find the 'qx' package there.
[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "ipython>=9.2.0",
]
