[project]
name = "qx"
version = "0.3.3"
description = "QX is a coding cli agent built by Transparently.AI"
authors = [{ name = "Transparently.AI", email = "mauro@transparently.ai" }]
dependencies = [
    "python-dotenv>=1.0.1",
    "rich>=13.7.1",
    "pyfzf>=0.0.8",
    "pydantic>=2.7.1",
    "openai>=1.23.6",
    "httpx>=0.27.0", # Added httpx for async client
    "prompt-toolkit>=3.0.51",
]
readme = "README.md"
requires-python = ">= 3.11"

[project.scripts]
qx = "qx.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/qx"]
